---
title: "Assigment - Data Driven Decision Making"
author: Nikita Blakenburg
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_notebook:
    toc: yes
    toc_depth: 2
---



<iframe width="560" height="315" src="https://www.youtube.com/embed/C6WKt6fJiso" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen data-external="1"></iframe>


## Why was data driven decision making (3DM) useful in this business case?

The Indian Minister of oil and three Indian oil companies decided that they wanted to open up 10,000 new PLG stations in India. The PLG stations needed to be profitable and sustainable, but also had to ensure that every one of the 1.2 billion people living in India would get access to an LPG Center within 10 kilometers of their homes. Data driven decision making was useful in this case because it would result in the ideal locations for the PLG stations.
 

## How did the organization apply 3DM?

Atlan, the company helping the government of India with this problem, started the project by collecting data. The way data is being collected and stored in India is often out-dated, written down on paper or isolated systems. An example of this is when Atlan did a previous project in India where they merged two data sets at a village level. Imagine the data set having a list of village names, after finishing the project it turned out that there was only a 15% match because of how places have different names and spelling in different regions.

There wasn't much data to work with for Atlan at the start of this project so they decided to map all of India's six hundred forty thousand villages. They now knew the location of the 1.2 billion citizens but before they could make further decisions they had to figure out where the existing PLG locations where. They uploaded an app and within a month there seventeen thousand distributers had donloaded the app and uploaded the location of there PLG station, making it possible for Atlan to map it down.

Now that the organization had the data sets they used an intelligent algorithm to deal with the differences in naming/spelling that we previous discussed. For example, that Palm Bay changed its name to Mumbai in 1995 and Pompona is often spelled Pumper.

They were left with a map that showed villages that did not have a PLG station and by looking at factors like road quality and accesibility they decided what the best places would be to place the stations. 

## What can the organization do with 3DM that they couldn’t do before?

What Atlan could do what they couldn't do before is make a data driven decision on how to benefit the most people by finding the right placement for 10,00 PLC stations.


